


name: Release plugin

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16.x"
            - name: Build
              run: |
                  npm install
                  npm run build
            - name: Zip for Release
              run: |
                  mkdir ${{ github.event.repository.name }}-${{ github.ref_name }}
                  cp main.js manifest.json styles.css ${{ github.event.repository.name }}-${{ github.ref_name }}
                  zip -r ${{ github.event.repository.name }}-${{ github.ref_name }}.zip ${{ github.event.repository.name }}-${{ github.ref_name }}
            - name: Create Release
              uses: ncipollo/release-action@v1
              with:
                  name: ${{ github.ref_name }}
                  artifacts: "*.zip,manifest.json,main.js,styles.css"
